name: gladgan
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - numpy
  - scikit-learn
  - matplotlib
  - graph-tool
  - pip
  - pandas
  - jsonpickle
  - fastparquet
  - pip:
    - networkx==2.0
